from __future__ import annotations

from typing import Any

class PodcastExtension:
    def itunes_author(self, author: str) -> None: ...
    def itunes_explicit(self, explicit: str) -> None: ...
    def itunes_owner(self, *, name: str, email: str) -> None: ...
    def itunes_image(self, url: str) -> None: ...
    def itunes_category(self, category: str) -> None: ...

class FeedEntry:
    podcast: PodcastExtension

    def title(self, title: str) -> None: ...
    def description(self, description: str) -> None: ...
    def pubDate(self, value: str | Any) -> None: ...
    def enclosure(self, url: str, length: str, type: str) -> None: ...
    def guid(self, guid: str, *, permalink: bool = False) -> None: ...

class FeedGenerator:
    podcast: PodcastExtension

    def load_extension(self, name: str, atom: bool = True, rss: bool = True) -> None: ...
    def title(self, title: str) -> None: ...
    def link(self, *, href: str, rel: str, **kwargs: Any) -> None: ...
    def description(self, description: str) -> None: ...
    def language(self, language: str) -> None: ...
    def rss_file(
        self,
        filename: str,
        extensions: bool = True,
        pretty: bool = False,
        encoding: str = "UTF-8",
        xml_declaration: bool = True,
    ) -> None: ...
    def add_entry(self) -> FeedEntry: ...

__all__ = ["FeedGenerator", "FeedEntry"]
