"""Generate exactly one GitHub Actions workflow from one pipeline config."""

from __future__ import annotations

import argparse
import pathlib
import sys

from tools.command_utils import detect_repo_context, ensure_repo_relative_path
from tools.pipeline_config import (
    PipelineConfig,
    load_pipeline_config,
    render_schedule_cron_entries,
)


def build_google_auth_mask_step() -> str:
    """Render a workflow step that masks Google auth metadata before auth runs.

    Inputs: none.
    Outputs: YAML for one GitHub Actions shell step.
    Edge cases: masks both the full provider path and its component values so
    later action logs redact whichever form appears. It also masks the runner
    workspace prefix and the `gha-creds-` filename prefix to reduce how much of
    the temporary credentials path is visible if the auth action logs it.
    """

    return """      - name: Mask Google auth metadata
        shell: bash
        run: |
          echo "::add-mask::${{ vars.GCP_PROJECT_ID }}"
          echo "::add-mask::${{ vars.GCP_PROJECT_NUMBER }}"
          echo "::add-mask::${{ vars.GCP_WIF_POOL_ID }}"
          echo "::add-mask::${{ vars.GCP_WIF_PROVIDER_ID }}"
          echo "::add-mask::projects/${{ vars.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ vars.GCP_WIF_POOL_ID }}/providers/${{ vars.GCP_WIF_PROVIDER_ID }}"
          echo "::add-mask::${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}"
          echo "::add-mask::${{ github.workspace }}"
          echo "::add-mask::gha-creds-"
"""


def generate_workflow_yaml(pipeline_config: PipelineConfig) -> str:
    """Render the full GitHub Actions workflow for one pipeline config.

    Inputs: validated pipeline config.
    Outputs: workflow YAML text.
    Edge cases: renders optional failure email steps only when configured.
    """

    schedule_entries = render_schedule_cron_entries(pipeline_config.schedule)
    google_auth_mask_step = build_google_auth_mask_step()
    schedule_lines = "\n".join(
        [
            "  schedule:",
            *[
                (
                    f"    - cron: '{schedule_entry['cron']}'\n"
                    f'      timezone: "{schedule_entry["timezone"]}"'
                )
                for schedule_entry in schedule_entries
            ],
        ]
    )

    runtime_env_lines = "\n".join(
        [
            "          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}",
            "          CF_PAGES_PROJECT: ${{ vars.CF_PAGES_PROJECT }}",
            "          CF_KV_NAMESPACE_ID: ${{ vars.CF_KV_NAMESPACE_ID }}",
            "          IA_ID_PREFIX: ${{ vars.IA_ID_PREFIX }}",
            "          PODCAST_MAX_RETRY_ATTEMPTS: ${{ vars.PODCAST_MAX_RETRY_ATTEMPTS }}",
            "          BILLING_EXPORT_TABLE: ${{ vars.BILLING_EXPORT_TABLE }}",
            "          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}",
            "          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}",
            "          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}",
        ]
    )

    failure_email_steps = ""
    if pipeline_config.failure_email is not None:
        failure_email_steps = f"""
      - name: Send failure email
        if: failure()
        continue-on-error: true
        env:
          SMTP_HOST: ${{{{ secrets.{pipeline_config.failure_email.smtp_host_secret_name} }}}}
          SMTP_PORT: ${{{{ secrets.{pipeline_config.failure_email.smtp_port_secret_name} }}}}
          SMTP_USERNAME: ${{{{ secrets.{pipeline_config.failure_email.smtp_username_secret_name} }}}}
          SMTP_PASSWORD: ${{{{ secrets.{pipeline_config.failure_email.smtp_password_secret_name} }}}}
          SMTP_FROM: ${{{{ secrets.{pipeline_config.failure_email.smtp_from_secret_name} }}}}
        run: |
          python3 -m tools.notify_failure \\
            --pipeline-id "{pipeline_config.pipeline_id}" \\
            --subject-prefix "{pipeline_config.failure_email.subject_prefix}" \\
            --recipients "{",".join(pipeline_config.failure_email.recipients)}" \\
            --log-path "${{{{ steps.run_pipeline.outputs.log_file }}}}" \\
            --exit-code "${{{{ steps.run_pipeline.outputs.exit_code }}}}"
"""

    return f"""# Generated by python -m tools.generate_workflow --pipeline {pipeline_config.pipeline_id}
# Source config: {pipeline_config.config_path.relative_to(pipeline_config.repo_root).as_posix()}
name: {pipeline_config.pipeline_id}

on:
  workflow_dispatch:
{schedule_lines}

permissions:
  contents: read
  id-token: write

jobs:
  run-pipeline:
    if: github.ref == '{pipeline_config.github.branch_ref}'
    runs-on: ubuntu-latest
    environment: {pipeline_config.github.environment_name}
    steps:
      - uses: actions/checkout@v5

{google_auth_mask_step}
      - uses: google-github-actions/auth@v3
        with:
          project_id: '${{{{ vars.GCP_PROJECT_ID }}}}'
          workload_identity_provider: 'projects/${{{{ vars.GCP_PROJECT_NUMBER }}}}/locations/global/workloadIdentityPools/${{{{ vars.GCP_WIF_POOL_ID }}}}/providers/${{{{ vars.GCP_WIF_PROVIDER_ID }}}}'
          service_account: '${{{{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}}}'
          create_credentials_file: true
          export_environment_variables: true

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Audio Dependencies
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Run selected pipeline
        id: run_pipeline
        shell: bash
        env:
{runtime_env_lines}
        run: |
          set +e
          mkdir -p out/logs
          log_file="out/logs/{pipeline_config.pipeline_id}.log"
          python3 run_feed.py "{pipeline_config.feed_slug}" 2>&1 | tee "$log_file"
          exit_code="${{PIPESTATUS[0]}}"
          echo "log_file=$log_file" >> "$GITHUB_OUTPUT"
          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
          exit "$exit_code"

      - name: Summarize failure
        if: failure()
        shell: bash
        run: |
          {{
            echo "### Pipeline failure"
            echo ""
            echo "- Pipeline: {pipeline_config.pipeline_id}"
            echo "- Exit code: ${{{{ steps.run_pipeline.outputs.exit_code }}}}"
            echo "- Log file: ${{{{ steps.run_pipeline.outputs.log_file }}}}"
            echo ""
            echo '```text'
            tail -n 80 "${{{{ steps.run_pipeline.outputs.log_file }}}}" || true
            echo '```'
          }} >> "$GITHUB_STEP_SUMMARY"
{failure_email_steps}"""  # nosec B608


def write_workflow_file(pipeline_config: PipelineConfig) -> pathlib.Path:
    """Write the generated workflow to the configured target path."""

    workflow_path = ensure_repo_relative_path(
        pipeline_config.repo_root,
        pipeline_config.github.workflow_file,
    )
    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    workflow_path.write_text(generate_workflow_yaml(pipeline_config), encoding="utf-8")
    return workflow_path


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for one-pipeline workflow generation."""

    parser = argparse.ArgumentParser(
        description="Generate exactly one GitHub Actions workflow from a pipeline config.",
    )
    parser.add_argument("--pipeline", help="Pipeline id under pipelines/<id>.yaml.")
    parser.add_argument("--config", help="Explicit pipeline config path.")
    args = parser.parse_args(argv)

    repo_context = detect_repo_context()
    pipeline_config = load_pipeline_config(
        repo_context.root,
        pipeline_id=args.pipeline,
        config_path=args.config,
    )
    workflow_path = write_workflow_file(pipeline_config)
    print(
        "Generated workflow for "
        f"{pipeline_config.pipeline_id}: {workflow_path.relative_to(repo_context.root)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
